apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-11-12T03:56:25Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: hello-app
  name: hello-app-service
  namespace: default
  resourceVersion: "357212"
  selfLink: /api/v1/namespaces/default/services/hello-app-service
  uid: e7ea5dc8-30ee-4304-85d9-f1ad71aa2e8a
spec:
  clusterIP: 10.3.241.83
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30879
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-app
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.64.233.162