apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-11-11T05:02:06Z"
  generation: 7
  labels:
    app: hello-app
  name: hello-app
  namespace: default
  resourceVersion: "357030"
  selfLink: /apis/apps/v1/namespaces/default/deployments/hello-app
  uid: 1649c3a8-aacd-414c-a001-270fca47fd20
spec:
  progressDeadlineSeconds: 600
  replicas: 10
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hello-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-app
    spec:
      containers:
      - image: gcr.io/psw7347/hello-app:v1
        imagePullPolicy: IfNotPresent
        name: hello-app
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 10
  conditions:
  - lastTransitionTime: "2020-11-11T05:02:06Z"
    lastUpdateTime: "2020-11-11T05:02:28Z"
    message: ReplicaSet "hello-app-d9cbcd7f5" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-11-12T03:56:29Z"
    lastUpdateTime: "2020-11-12T03:56:29Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 7
  readyReplicas: 10
  replicas: 10
  updatedReplicas: 10