apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-11-12T08:12:07Z"
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: hello-app
  name: hello-app-service
  namespace: default
  resourceVersion: "422579"
  selfLink: /api/v1/namespaces/default/services/hello-app-service
  uid: 1d08eaae-7015-4b3b-a8c6-6d41a2639dee
spec:
  clusterIP: 10.3.241.68
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 30536
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: hello-app
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 34.64.233.162