apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2020-11-12T08:11:49Z"
  generation: 6
  labels:
    app: hello-app
  name: hello-app
  namespace: default
  resourceVersion: "425077"
  selfLink: /apis/apps/v1/namespaces/default/deployments/hello-app
  uid: 54795a67-5e84-4bf6-a0ce-66358930a844
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hello-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-app
    spec:
      containers:
        - image: gcr.io/psw7347/hello-app:v2
          imagePullPolicy: IfNotPresent
          name: hello-app
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
    conditions:
        - lastTransitionTime: "2020-11-12T08:12:40Z"
          lastUpdateTime: "2020-11-12T08:12:40Z"
          message: Deployment has minimum availability.
          reason: MinimumReplicasAvailable
          status: "True"
          type: Available
          - lastTransitionTime: "2020-11-12T08:11:49Z"
            lastUpdateTime: "2020-11-12T08:16:38Z"
            message: ReplicaSet "hello-app-74cfdf466b" has successfully progressed.
            reason: NewReplicaSetAvailable
            status: "True"
            type: Progressing
    observedGeneration: 6
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1