apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-11-12T04:38:44Z"
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: hello-app
  name: hello-app-service
  namespace: default
  resourceVersion: "368259"
  selfLink: /api/v1/namespaces/default/services/hello-app-service
  uid: 94b63928-1de9-44e6-af04-4037a632d000
spec:
  clusterIP: 10.3.254.224
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 32297
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: hello-app
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 34.64.245.122