apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-11-12T04:38:20Z"
  generation: 4
  labels:
    app: hello-app
  name: hello-app
  namespace: default
  resourceVersion: "368497"
  selfLink: /apis/apps/v1/namespaces/default/deployments/hello-app
  uid: 2346f07b-50cb-4c00-a49d-17ccfa605bce
spec:
  progressDeadlineSeconds: 600
  replicas: 10
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hello-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-app
    spec:
      containers:
        - image: gcr.io/psw7347/hello-app:v1
          imagePullPolicy: IfNotPresent
          name: hello-app
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 10
    conditions:
        - lastTransitionTime: "2020-11-12T04:38:20Z"
          lastUpdateTime: "2020-11-12T04:38:22Z"
          message: ReplicaSet "hello-app-d9cbcd7f5" has successfully progressed.
          reason: NewReplicaSetAvailable
          status: "True"
          type: Progressing
          - lastTransitionTime: "2020-11-12T04:40:11Z"
            lastUpdateTime: "2020-11-12T04:40:11Z"
            message: Deployment has minimum availability.
            reason: MinimumReplicasAvailable
            status: "True"
            type: Available
    observedGeneration: 4
    readyReplicas: 10
    replicas: 10
    updatedReplicas: 10